name: Continuous Integration Tests

on:
  pull_request:
    branches: [ main ]
concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true  

jobs:

  ci_test:
    name: Clickhouse CI
    timeout-minutes: 5
    runs-on: ubuntu-latest
    services:
      clickhouse:
        image: clickhouse/clickhouse-server:22.8
        ports:
          - 9000:9000
          - 8443:8443
    container:
      image: ghcr.io/kzzzr/airbyte_lab:ci
      env:
        S3_BUCKET_NAME: analytics-engineering-airbyte20230619191221397100000001 # Fill in your own bucket name!
    steps:
      - uses: actions/checkout@v3
      - run: dbt --version
      - run: dbt debug --target ci
      - run: dbt deps --target ci
      - run: dbt build --target ci
